# -*- coding: utf-8 -*-
"""Linked_listipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C9Tof73FUQ33ax5zLIarag4ONEznvj0i
"""

# Implementing a single Node

class Node:


  def __init__(self, value):
      self.data = value
      self.next = None

a = Node(13)
b = Node(20)
c = Node(11)

print(a)

print(a.data)

print(a.next)

a.next=b

print(b)

print(a.next)

b.next = c

print(c)

print(b.next)



"""2 . Insertion In a single linked list

Following steps:-
create a new node
Add of a new node will point to the current head node

Reassingn the Head to new node
"""

class LinkedList:

  def __init__(self):
    self.head = None

  def insert(self,value):

    # 1. create a new node with the given value

    new_node = Node(value)

    # 2. point the address pointer of new node -> head

    new_node.next = self.head

    # 3. Reassign head to new node
    self.head = new_node

ll = LinkedList()
ll.insert(10)
ll.insert(20)
ll.insert(30)

"""# Traversal in a Singly Linked list
1) temp = head
2) while temp is not Null:
print(temp.data)
temp = temp.next


"""

def traverse(self):
  temp = self.head

  while temp is not None:
    print(temp.data, end=" ")
    temp = temp.next

ll = LinkedList()
ll.insert(10)
ll.insert(20)
ll.insert(30)
ll.insert(78)

class LinkedList:

  def __init__(self):
    self.head = None

  def insert(self,value):
    new_node = Node(value)
    new_node.next = self.head
    self.head = new_node

  def delete_head(self):
    if self.head is None:
      print("Cant be deleted, linked list is empty")
    else:
      self.head = self.head.next

  def delete_tail(self):
    if self.head is None:
      print("List is empty. Cannot delete tail.")
      return
    if self.head.next is None: # Only one node in the list
      self.head = None
      return
    temp = self.head
    while temp.next.next is not None:
      temp = temp.next

    temp.next = None

  def delete_item(self, value):
    if self.head is None:
      print("List is empty. Cannot delete.")
      return

    # Case 1: Head itself holds the value to be deleted
    if self.head.data == value:
      self.head = self.head.next
      return

    # Case 2: Search for the value to be deleted, keeping track of the previous node
    temp = self.head
    # Iterate until we find the node *before* the one to be deleted, or reach the end
    while temp.next is not None and temp.next.data != value:
      temp = temp.next

    # If temp.next is not None, it means we found the node to delete (temp.next)
    if temp.next is not None:
      temp.next = temp.next.next # Bypass the node to be deleted
    else:
      print("Item not Found:")

  def traverse(self):
    temp = self.head
    while temp is not None:
      print(temp.data, end=" ")
      temp = temp.next

# Now, let's create a new LinkedList instance using the corrected class definition
# and demonstrate the traverse method.
ll_corrected = LinkedList()
ll_corrected.insert(10)
ll_corrected.insert(20)
ll_corrected.insert(30)
ll_corrected.insert(78)

# Call the traverse method on the new instance
ll_corrected.traverse()

ll_corrected.insert(90)

ll_corrected.traverse()

"""Insertion After A node sll"""

# first find out the node
# new.next=prev.next
# prev.next = new

def insert_after







"""# Deletion a Node

"""

# 1 deletion head
ll = LinkedList()
ll.insert(20)
ll.insert(30)
ll.insert(78)

ll.traverse()

ll.delete_head()

ll.traverse()

ll.delete_head()

ll.traverse()

ll.delete_head()

"""# Delete Node from The last node"""

ll = LinkedList()
ll.insert(1)
ll.insert(4)
ll.insert(5)

ll.traverse()

ll.delete_tail()

ll.traverse()

ll.delete_tail()

ll.traverse()

"""# Deleting a node by value"""

ll = LinkedList()
ll.insert(1)
ll.insert(4)
ll.insert(5)
ll.insert(6)

ll.traverse()

ll.delete_item(6)

ll.traverse()

ll.delete_item(4)

ll.traverse()

ll.delete_item(100)

